Fix flaky `TestJoinMembersWithRetryBackoff`
```
    memberlist_client_test.go:898:
        	Error Trace:	/Users/dimitar/grafana/dskit/kv/memberlist/memberlist_client_test.go:898
        	            				/Users/dimitar/grafana/dskit/kv/memberlist/asm_arm64.s:1197
        	Error:      	Received unexpected error:
        	            	Member-2 failed to join the cluster: &{[%!f(*errors.errorString=&{Failed to join 127.0.0.1:57493: dial tcp 127.0.0.1:57493: connect: connection refused})] %!f(multierror.ErrorFormatFunc=<nil>)}
        	Test:       	TestJoinMembersWithRetryBackoff/Test_late_start_of_DNS_service
```

The failure was caused by the test clients starting and expecting to connect to a KV which still wasn't started.
This is unrelated with the backoff that the test asserts on (the backoff happens effectively in the call `err = services.StartAndAwaitRunning(context.Background(), mkv)`).